# Core Interface
cursor                #f0f0f0
cursor_text_color     #4c4c4c

foreground            #e7e7e7
background            #1a1a1a
selection_foreground  #ffffff
selection_background  #4f4539
url_color             #9ec49f

# Black (The base shadows)
color0                #1a1a1a
color8                #4c4c4c

# Red (Muted clay)
color1                #ba1a1a
color9                #c49ea0

# Green (The 'Chill' Sage)
color2                #6F8052
color10               #9ec49f

# Yellow (Sand/Wheat)
color3                #aca98a
color11               #c4c19e

# Blue (Deep Earth/Wood)
color4                #805611
color12               #a39ec4

# Magenta (Dried Rose)
color5                #ba1a1a
color13               #c49ec4

# Cyan (Cool Slate)
color6                #3C4444
color14               #9ec3c4

# White (Off-white/Grey)
color7                #dec2a1
color15               #f0f0f0
